cache:
  key: "${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"
  paths:
    - .cache/

include:
  - component: $CI_SERVER_FQDN/components/stagefreight/gl-docker-release@main
    inputs:
      gitlab_domain: "https://gitlab.prplanit.com"
      gitlab_token: "${GITLAB_TOKEN}"
      docker_release_path: "prplanit/$CI_PROJECT_NAME"
      freight_docker_url_1: "docker.io"
      freight_docker_user_1: "${DOCKER_HUB_USERNAME}"
      freight_docker_pass_1: "${DOCKER_HUB_PASSWORD}"
      freight_docker_path_1: "prplanit/$CI_PROJECT_NAME"
      freight_docker_registry_1: "docker"
  - project: 'components/stagefreight'
    file: '/export-dependencies.yml'
    ref: main
        
stages:
  - build
  - release